keys:
  - &main    age10smz367wn4dfdq8ufgku5d7q7de9qvdzdn6h2d8szmta9hws7v2sup9r6p
  - &t460p   age1c8ex4vam0qx6kldl3w2tddhmejxkrlf90mmfe334myq2l9cnfq9sgehs5d
  - &xps8930 age1ynhrpsfdwxm3ryzn6uyvqng5hca2em983qm6d8jkkhyq6u0w8qpq3gxxh0
  - &x200s   age1naq9xtdmugcede56kpgfu8tu3gq20g6tgrt2x3vz08ge86rwvpqqfxaw2e
  - &portal  age1wg2vpgh5wx4vn5zst08axx9xvws7y0vs8u8kn8qljlppegy6kdxqs7r5ws
  - &vm-test age17cg7mctcy03vt7wckfezc0xv2ntanhqx48uma9x2cltxatg2dstqx45xhu

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *main
      - *t460p
      - *xps8930
      - *x200s
      - *portal
  - path_regex: modules/sops/vm-test/test-secrets\.yaml$
    key_groups:
    - age:
      - *main
      - *vm-test
