keys:
  - &main       age10smz367wn4dfdq8ufgku5d7q7de9qvdzdn6h2d8szmta9hws7v2sup9r6p
  - &t460p      age1c8ex4vam0qx6kldl3w2tddhmejxkrlf90mmfe334myq2l9cnfq9sgehs5d
  - &xps8930    age1ynhrpsfdwxm3ryzn6uyvqng5hca2em983qm6d8jkkhyq6u0w8qpq3gxxh0
  - &x200s      age1naq9xtdmugcede56kpgfu8tu3gq20g6tgrt2x3vz08ge86rwvpqqfxaw2e
  - &nexusbytes age1xya6kmcpxw6n6xdp8pnl5kzhpu39vpfqn73cg9su8rvw63r89y8qc3xmy9
  - &vultr      age1knaw8w3lmmnwgncn65fegan62jkkpzg4hgqmpvaagqk8x26x5qlqs42efv
  - &vm-test    age17cg7mctcy03vt7wckfezc0xv2ntanhqx48uma9x2cltxatg2dstqx45xhu

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *main
      - *t460p
      - *xps8930
      - *x200s
      - *nexusbytes
      - *vultr
  - path_regex: modules/sops/vm-test/test-secrets\.yaml$
    key_groups:
    - age:
      - *main
      - *vm-test
