keys: &keys
  - &t460p age1c8ex4vam0qx6kldl3w2tddhmejxkrlf90mmfe334myq2l9cnfq9sgehs5d
  - &xps8930 age1ynhrpsfdwxm3ryzn6uyvqng5hca2em983qm6d8jkkhyq6u0w8qpq3gxxh0
  - &x200s age1naq9xtdmugcede56kpgfu8tu3gq20g6tgrt2x3vz08ge86rwvpqqfxaw2e
  - &portal age1wg2vpgh5wx4vn5zst08axx9xvws7y0vs8u8kn8qljlppegy6kdxqs7r5ws

creation_rules:
  - path_regex: secrets/common.yaml$
    key_groups:
    - age: *keys
  - path_regex: secrets/workstations.yaml$
    key_groups:
    - age:
      - *t460p
      - *xps8930
  - path_regex: secrets/x200s.yaml$
    key_groups:
    - age:
      - *t460p
      - *xps8930
      - *x200s
  - path_regex: secrets/portal.yaml$
    key_groups:
    - age:
      - *t460p
      - *xps8930
      - *portal
