keys:
  - &main       7D2F4C6B9A8300CCDDB641FDDF14B55A7A29C30F
  - &github     age143hpp7hqp4708z2dy868llsj8u9lc2jyq59ahnzusjvwg5g2u3cs3jaltg
  - &t460p      age1c8ex4vam0qx6kldl3w2tddhmejxkrlf90mmfe334myq2l9cnfq9sgehs5d
  - &xps8930    age1ynhrpsfdwxm3ryzn6uyvqng5hca2em983qm6d8jkkhyq6u0w8qpq3gxxh0
  - &x200s      age1naq9xtdmugcede56kpgfu8tu3gq20g6tgrt2x3vz08ge86rwvpqqfxaw2e
  - &nuc        age1pf99e6kfd52kugec6t27t9nkere8vn3guk5t04v7ldde4cnlwpwsm0n4gj
  - &rica       age1eele84f8nufp7g2j8cws8z2su0kp9ldgcvj8gmgldc326j7ykv9qzxcuaa
  - &vultr      age1knaw8w3lmmnwgncn65fegan62jkkpzg4hgqmpvaagqk8x26x5qlqs42efv
  - &tencent    age1wzm6xztn2m08qr74hg29nv2qlz8537apl4kcqakfyg3gc8l0mcgstrqjpf
  - &g150ts    age1vxyz8za0se99gcne8yzzez7lx3w7jf9rlg7a0qt4gt7q03ca7urquhun6a
  - &aws        age1m6tfhx22rdfd27v2666lqskpuag6fqz9rfdquqv4cktg88mv64yqusulpa
  - &vm-test    age17cg7mctcy03vt7wckfezc0xv2ntanhqx48uma9x2cltxatg2dstqx45xhu

creation_rules:
  - path_regex: ^secrets/terraform-inputs\.yaml$
    key_groups:
    - pgp:
      - *main
      age:
      - *github
  # terraform inputs shared with rica
  - path_regex: ^secrets/hosts/rica-terraform\.yaml$
    key_groups:
    - pgp:
      - *main
      age:
      - *rica
      - *github
  - path_regex: ^secrets/terraform-outputs(\.plain)?\.yaml$
    key_groups:
    - pgp:
      - *main
      age:
      - *t460p
      - *xps8930
      - *x200s
      - *nuc
      - *rica
      - *vultr
      - *tencent
      - *aws
  - path_regex: terraform.tfstate$
    key_groups:
    - pgp:
      - *main
      age:
      - *github
  - path_regex: terraform.plan$
    key_groups:
    - age:
      - *github
  - path_regex: ^secrets/(terraform/)?common(\.plain)?\.yaml$
    key_groups:
    - pgp:
      - *main
      age:
      - *t460p
      - *xps8930
      - *x200s
      - *nuc
      - *rica
      - *vultr
      - *tencent
      - *aws
      # no age key for g150ts
  - path_regex: ^secrets/(terraform/)?infrastructure(\.plain)?\.yaml$
    key_groups:
    - pgp:
      - *main
      age:
      - *t460p
      - *xps8930
      - *x200s
      - *nuc
      - *rica
      - *vultr
      - *tencent
      - *aws
      - *g150ts
  - path_regex: ^secrets/(terraform/)?hosts/t460p(\.plain)?\.yaml$
    key_groups:
    - pgp:
      - *main
      age:
      - *t460p
  - path_regex: ^secrets/(terraform/)?hosts/nuc(\.plain)?\.yaml$
    key_groups:
    - pgp:
      - *main
      age:
      - *nuc
  - path_regex: ^secrets/(terraform/)?hosts/xps8930(\.plain)?\.yaml$
    key_groups:
    - pgp:
      - *main
      age:
      - *xps8930
  - path_regex: ^secrets/(terraform/)?hosts/x200s(\.plain)?\.yaml$
    key_groups:
    - pgp:
      - *main
      age:
      - *x200s
  - path_regex: ^secrets/(terraform/)?hosts/vultr(\.plain)?\.yaml$
    key_groups:
    - pgp:
      - *main
      age:
      - *vultr
  - path_regex: ^secrets/(terraform/)?hosts/tencent(\.plain)?\.yaml$
    key_groups:
    - pgp:
      - *main
      age:
      - *tencent
  - path_regex: ^secrets/(terraform/)?hosts/rica(\.plain)?\.yaml$
    key_groups:
    - pgp:
      - *main
      age:
      - *rica
  - path_regex: ^secrets/(terraform/)?hosts/aws(\.plain)?\.yaml$
    key_groups:
    - pgp:
      - *main
      age:
      - *aws
  - path_regex: ^secrets/(terraform/)?hosts/g150ts(\.plain)?\.yaml$
    key_groups:
    - pgp:
      - *main
      age:
      - *g150ts
  - path_regex: ^modules/sops/vm-test/test-secrets/.*\.yaml$
    key_groups:
    - pgp:
      - *main
      age:
      - *vm-test
