# nvfetcher.toml
[manix]
src.git = "https://github.com/mlvzk/manix"
fetch.github = "mlvzk/manix"

[idris2-mode]
src.git = "https://github.com/redfish64/idris2-mode"
fetch.github = "redfish64/idris2-mode"
